---
- hosts: nexus_server
  become: yes
  vars:
    url: "http://actual-valid-url/nexus-3.70.1-02-java11-unix.tar.gz"
    owner: nexus
    group: nexus

  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Installation of Java 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Create Nexus user
      user:
        name: nexus
        shell: /bin/bash

    - name: Debug Nexus URL
      debug:
        msg: "Nexus URL is {{ url }}"

    - name: Downloading Nexus
      get_url:
        url: "{{ url }}"
        dest: "/tmp/nexus-3.70.1-02-java11-unix.tar.gz"

    - name: Extract the Nexus tar file
      unarchive:
        src: "/tmp/nexus-3.70.1-02-java11-unix.tar.gz"
        dest: "/"
        remote_src: yes

    - name: Remove tar file
      file:
        path: "/tmp/nexus-3.70.1-02-java11-unix.tar.gz"
        state: absent

    - name: Set ownership and group on Nexus directory to nexus
      file:
        path: "/nexus-3.70.1-02"
        owner: "{{ owner }}"
        group: "{{ group }}"
        state: directory
        recurse: yes

    - name: Set ownership on Nexus data directory
      file:
        path: "/sonatype-work"
        owner: "{{ owner }}"
        group: "{{ group }}"
        state: directory
        recurse: yes

    - name: Configure Nexus to run as the nexus user
      lineinfile:
        path: "/nexus-3.70.1-02/bin/nexus.rc"
        line: "run_as_user=nexus"

    - name: Create systemd file for Nexus
      template:
        src: ./nexus.service
        dest: /etc/systemd/system/nexus.service

    - name: Reload systemd to apply Nexus service
      systemd:
        daemon_reload: yes

    - name: Enable and start Nexus service
      systemd:
        name: nexus
        enabled: yes
        state: started
