---
- name: Install Nexus
  hosts: nexus_server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add OpenJDK repository
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /tmp/nexus.tar.gz

    - name: Extract Nexus
      unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create symlink for Nexus
      file:
        src: /opt/nexus-3.*
        dest: /opt/nexus
        state: link

    - name: Create Nexus user
      user:
        name: nexus
        shell: /bin/bash
        create_home: yes

    - name: Change ownership of Nexus directory
      file:
        path: /opt/nexus
        owner: nexus
        group: nexus
        recurse: yes

    - name: Start Nexus
      shell: |
        su - nexus -c "/opt/nexus/bin/nexus start"

- name: Install MicroK8s
  hosts: kubernetes
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Snap
      apt:
        name: snapd
        state: present
