---
- name: Install Nexus
  hosts: nexus_server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add OpenJDK repository
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present

    - name: Install Java 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Download Nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /tmp/nexus.tar.gz

    - name: Extract Nexus
      unarchive:
        src: /tmp/nexus.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Find Nexus directory
      find:
        paths: /opt/
        patterns: 'nexus-*'
        file_type: directory
      register: nexus_dirs

    - name: Debug Nexus directory path
      debug:
        msg: "Nexus directory found: {{ nexus_dirs.files[0].path }}"

    - name: Create symlink for Nexus
      file:
        src: "{{ nexus_dirs.files[0].path }}"
        dest: /opt/nexus
        state: link

    - name: Change ownership of Nexus directory
      file:
        path: "{{ nexus_dirs.files[0].path }}"
        owner: nexus
        group: nexus
        recurse: yes

    - name: Set INSTALL4J_JAVA_HOME environment variable
      lineinfile:
        path: /etc/environment
        line: 'INSTALL4J_JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"'
        create: yes

    - name: Start Nexus
      shell: |
        source /etc/environment
        su - nexus -c "/opt/nexus/bin/nexus start"
